jenkins-infra/account-app

- pom.xml
- src/main/java/org/jenkinsci/account/Application.java
- src/main/resources/org/jenkinsci/account/Application/signup.jelly
Copied some code from http://www.journaldev.com/7133/how-to-integrate-google-recaptcha-in-java-web-application
> INFRA-550 - First stab at reCAPTCHA 2.

- src/main/java/org/jenkinsci/account/Application.java
Sort various blacklists, and add some new elements.
> Allow the IP blacklist allow to block whole subnets

- src/main/java/org/jenkinsci/account/Application.java
Encode the URL, but not the subject.
> Check use is not same as a name element

- src/main/java/org/jenkinsci/account/Application.java
> Fix used for check.

- src/main/java/org/jenkinsci/account/Application.java
> Fix non routable IP address being used for checks

- src/main/java/org/jenkinsci/account/Application.java
But only for ones that don't have another block reason. Limit the scope of that information to people who don't have other spammer type qualities about their request.
Add more updates to the blacklists.
> Provide a useful message for existing emails

- src/main/java/org/jenkinsci/account/Application.java
If the email is already used by an account, don't consider that spam, but give them a password reset link.
> Remove a few blacklist items.

- Dockerfile
- Jenkinsfile
- Makefile
- README.md
- build.gradle
- config.properties.example
- docker-compose.yaml
- entrypoint.sh
- src/main/java/org/jenkinsci/account/Application.java
- src/main/java/org/jenkinsci/account/BoardElection.java
- src/main/java/org/jenkinsci/account/Myself.java
- src/main/java/org/jenkinsci/account/Parameters.java
- src/main/resources/org/jenkinsci/account/AdminUI/signup.jelly
- src/main/resources/org/jenkinsci/account/Application/index.jelly
- src/main/resources/org/jenkinsci/account/Application/login.jelly
- src/main/resources/org/jenkinsci/account/Application/passwordReset.jelly
- src/main/resources/org/jenkinsci/account/Application/signup.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/configure.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/done.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/index.jelly
- src/main/resources/org/jenkinsci/account/Myself/index.jelly
- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
- src/main/webapp/WEB-INF/web.xml
I adapted the nice work done by @ndeloof from PR [#96](https://github.com/jenkins-infra/account-app/pull/96) and made some fixes and improvements.
Bugs:
* Within Boardelection form, drag&drop wasn't working anymore because of Jquery broken links.
-> Jquery is now packages with the application (no external links)
* Variable 'electionLogfile' wasn't taken into account
-> I changed electionLogfile to electionLogdir as the account app only need to know where to create election log files
* All votes where stored in a simple text file which had several limitations.
-> I am now storing votes in a yaml file, with one yaml file per election
* Change 'commons-jelly-tags-define' library
-> commons-jelly:commons-jelly-tags-define:1.0
I still don't know why but I had several issues with …
> BoardElections && CSS improvements

- README.md
- config.properties.example
- entrypoint.sh
- src/main/java/org/jenkinsci/account/Application.java
- src/main/java/org/jenkinsci/account/Parameters.java
* Update README with SMTP configurations options
* Update entrypoint.sh with new SMTP configurations
* Add username,password with starttls authentication on port 587 for SMTP server
> [INFRA-1210] Accountapp: Add Auth options for SMTP server

- Makefile
- docker-compose.yaml
- env.sandbox
- src/main/resources/org/jenkinsci/account/AdminUI/newPassword.jelly
- src/main/resources/org/jenkinsci/account/AdminUI/search.jelly
- src/main/resources/org/jenkinsci/account/AdminUI/signup.jelly
- src/main/resources/org/jenkinsci/account/Application/done.jelly
- src/main/resources/org/jenkinsci/account/Application/doneMail.jelly
- src/main/resources/org/jenkinsci/account/Application/index.jelly
- src/main/resources/org/jenkinsci/account/Application/login.jelly
- src/main/resources/org/jenkinsci/account/Application/passwordReset.jelly
- src/main/resources/org/jenkinsci/account/Application/signup.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/configure.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/done.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/index.jelly
- src/main/resources/org/jenkinsci/account/Myself/done.jelly
- src/main/resources/org/jenkinsci/account/Myself/index.jelly
- src/main/resources/org/jenkinsci/account/UserError/index.jelly
- src/main/resources/org/jenkinsci/account/openid/JenkinsOpenIDSession/confirm.jelly
- src/main/resources/org/jenkinsci/account/openid/JenkinsOpenIDSession/index.jelly
- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
In order to test this PR, you can go to the root directory of the project then execute: 
`make sandbox` (required docker)
Then go to http://localhost:8080
> Fix XSS vulnerabilities

- src/main/java/org/jenkinsci/account/Application.java
- src/main/resources/org/jenkinsci/account/Application/resetMail.jelly
Always display following message when we reset a password:
" If your user account or email address exists in our database, you will receive a password at your email address in a few minutes"
Display following message if login doesn't work (wrong password or email)
"Oops!
User "t" not found or password incorrect"
> [INFRA-1298] Update reset password and login message

- Dockerfile
- src/main/java/org/jenkinsci/account/Application.java
- src/main/java/org/jenkinsci/account/UserError.java
- src/main/resources/org/jenkinsci/account/UserError/index.jelly
Make sure stacktraces don't appear when empty username/password is entered. See https://issues.jenkins-ci.org/browse/WEBSITE-710
> [WEBSITE-710] Add check for empty username / password

- entrypoint.sh
Based on this [PR](https://github.com/jenkins-infra/jira-ldap-syncer/pull/1), it allows change the jira-ldap-syncer configuration
> Add username and basedn configuration for jira-ldap-syncer

- src/main/resources/org/jenkinsci/account/UserError/index.jelly
Fixes https://github.com/jenkins-infra/helpdesk/issues/2730
Part of https://github.com/jenkins-infra/helpdesk/issues/9
> chore: replace issues.jenkins.io/project/INFRA by jenkins-infra/helpdesk

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> chore: enable release-drafter

- renovate.json
Closes #156 
Closes #155 
Closes #154 
Closes #152
> chore: Ban a few dependencies

- renovate.json
https://github.com/jenkins-infra/account-app/issues/169#issuecomment-1286628070
> fix: Make renovate work again

- Dockerfile
- Jenkinsfile
- build.gradle.kts
- src/it/java/org/jenkinsci/account/ui/BaseTest.java
- src/it/java/org/jenkinsci/account/ui/LoginPage.java
- src/it/java/org/jenkinsci/account/ui/LoginTest.java
- src/it/resources/org/jenkinsci/account/ui/test-data.ldif
relates to https://github.com/jenkins-infra/account-app/issues/166
> Initial UI test to make sure login works

- build.gradle.kts
- src/it/java/org/jenkinsci/account/ui/BaseTest.java
- src/it/java/org/jenkinsci/account/ui/admin/AdminPage.java
- src/it/java/org/jenkinsci/account/ui/admin/DeleteUserTest.java
- src/it/java/org/jenkinsci/account/ui/admin/ResetPasswordAdminTest.java
- src/it/java/org/jenkinsci/account/ui/myaccount/MyProfilePage.java
- src/it/java/org/jenkinsci/account/ui/myaccount/UpdateMyAccountTest.java
- src/it/java/org/jenkinsci/account/ui/resetpassword/ResetPasswordTest.java
- src/it/java/org/jenkinsci/account/ui/resetpassword/UserLookupType.java
- src/main/java/org/jenkinsci/account/Myself.java
Part of https://github.com/jenkins-infra/account-app/issues/166
> Add delete user and self service update tests

- src/it/java/org/jenkinsci/account/ui/BaseTest.java
- src/main/resources/org/jenkinsci/account/AdminUI/signup.jelly
- src/main/resources/org/jenkinsci/account/Application/login.jelly
- src/main/resources/org/jenkinsci/account/Application/passwordReset.jelly
- src/main/resources/org/jenkinsci/account/Application/signup.jelly
- src/main/resources/org/jenkinsci/account/Myself/index.jelly
- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
- src/main/webapp/style.css
Fixes #197 
Also Tether is no longer needed since components are used for popups. If any other popups outside of header get implemented in the future, Popper should be used instead of Tether.
> Add spacing to forms, remove tether

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
Don't index our tooling anylonger
> Apply 'noindex' rule to tool

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
Fixes #250
Alternative to #251 which doesn't pass tests
> Revert the use of jenkins-io-component for now

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
Fixes https://github.com/jenkins-infra/account-app/issues/250
> Drop position attribute for footer

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
If there is enough content to fill the screen, footer should not be in the view.
Fixes https://github.com/jenkins-infra/account-app/issues/257
> Footer shouldn't be fixed

- Jenkinsfile
> chore: build Docker image on `ci.jenkins.io` too

- Jenkinsfile_k8s
as per https://github.com/jenkins-infra/helpdesk/issues/3619
> feat(docker build): build for both amd64 and arm64 to prepare migration on arm64 nodepool

- src/main/java/org/jenkinsci/account/Application.java
https://github.com/jenkins-infra/helpdesk/issues/4229#issuecomment-2285861361
> Block spammer

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
Ref. https://github.com/jenkins-infra/helpdesk/issues/4238
> feat: do not index followed links
