- src/main/java/org/jenkinsci/account/Application.java
Move cookie creation before circuit breaker, so we get a better idea of who is clearing their cache when the circuit breaker is set, but we still know of previous items are catching them.
> Block some IP's that are tripping the circuit breaker a lot.

- src/main/java/org/jenkinsci/account/Application.java
Also disallow sdfg type userids that also contain numbers (usually at the end, but sometimes at the start)
Also remove link from google groups page, to thwart most spammers from hitting the dev list with spam.
> Change to check stopforumspam after we check our out list of checks.

- src/main/java/org/jenkinsci/account/Application.java
Reformatted a bit to make it more readable + added requirement to
explain why people need an account, so that it's easier and quicker for
infra team to decide it's likely a real user or an effin' spammer.
> Try and accelerate the spammer triage process

- pom.xml
Dependency on org.kohsuke.stapler:stapler was declared twice: on 1.203
and 1.233.
Kept the 1.233 after having checked with `mvn dependency:list` it was
actually the one being currently chosen by the maven resolution
strategy.
> Fixed warning about duplicate dependency

- Dockerfile
- README.md
- bin/run.sh
- build.gradle
This makes things *much* more sane and easy to maintain, since we're just
grabbing the base image directly from the Jetty project.
> Update the container to use the official jetty image

- src/main/java/org/jenkinsci/account/Application.java
Some mail clients will select it when copying, and users have problems signing in, not noticing it.
> Remove trailing space after password in email.

- .gitignore
- Dockerfile
- README.md
- config.properties.example
- docker-compose.yaml
- entrypoint.sh
This PR add an additional way to configure 'accountapp' trough environment variables that simplify deployment on kubernetes cluster.
I added a docker-compose file only for testing purpose.
! This PR doesn't take into account [#96](https://github.com/jenkins-infra/account-app/pull/96) as it is not up to date with master.
> Add application configuration through env variables

- src/main/java/org/jenkinsci/account/Application.java
- src/main/java/org/jenkinsci/account/BoardElection.java
- src/main/java/org/jenkinsci/account/Myself.java
- src/main/java/org/jenkinsci/account/Parameters.java
- src/main/resources/org/jenkinsci/account/Application/index.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/configure.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/done.jelly
- src/main/resources/org/jenkinsci/account/BoardElection/index.jelly
Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>
require some extra configuration parameters:
> Web UI to manage board election

- Dockerfile
- src/main/java/org/jenkinsci/account/Application.java
- src/main/java/org/jenkinsci/account/SystemError.java
- src/main/resources/org/jenkinsci/account/SystemError/index.jelly
I don't know if it's the best way to solve this. 
To make it short, some java string may contain untrusted or trusted html  and I don't know if it's possible to disable html escaping at the java level
> [INFRA-1347] Doesn't escape all html error message

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
Some links are currently broken on the accounts app. Most notably the links in the footer columns "Resources" and "Solutions" are, but this also affects the favicon.
> Add the jenkins.io domain to some broken resources

- .gitignore
- src/main/java/org/jenkinsci/account/AdminUI.java
- src/main/java/org/jenkinsci/account/Application.java
- src/main/resources/org/jenkinsci/account/Application/index.jelly
This change ensures that a user gets email notification when a password is reset from the Web UI form or from a REST API call. It also allows specifying a password reset reason which can be passed through UI or through a REST API.
Additional bugfixes:
* Prevent NullPointerException when board elections are not configured in settings (default to disabled)
* Prevent NullPointerException when SMTP auth flag is not set explicitly (`Boolean` FTM)
> Send email notification when resetting passwords + minor fixes and enhancements

- src/main/java/org/jenkinsci/account/AdminUI.java
- src/main/java/org/jenkinsci/account/Application.java
> /admin/doSignup: Allow hiding the temporary password and adding a message to the email

- Dockerfile
- README.md
- env.sandbox
- src/main/resources/org/jenkinsci/account/Application/doneMail.jelly
- src/main/resources/org/jenkinsci/account/Application/index.jelly
- src/main/resources/org/jenkinsci/account/UserError/index.jelly
- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
The default jira url is now wiki.jenkins.io
Signed-off-by: Olivier Vernin <olivier@vernin.me>
> Update jira url to issues.jenkins.io

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
What it looks like right now
What it looks like with web component:
I realized there's a need to allow sites to extend the nav bar, so i'll add support for it, but I still think its a possible win.
> Switch to using web component version of nav bar

- Dockerfile
Minor QoL change to download the datadog agent from a sane URL.
Bonus points: This is something renovate picks up and and maintains itself.
> Don't download the dd agent through the frontend

- Dockerfile
Caused by https://github.com/jenkins-infra/account-app/pull/160 (spaces around the env var at first sight)
Fixes the following build error:
```console
Step 19/31 : ADD [https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/$DD_AGENT_VERSION/dd-java-agent-"$DD_AGENT_VERSION".jar](https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/$DD_AGENT_VERSION/dd-java-agent-%22$DD_AGENT_VERSION%22.jar) /home/jetty/dd-java-agent.jar
ADD failed: failed to GET https://repo1.maven.org/maven2/com/datadoghq/dd-java-agent/= 0.9.0/dd-java-agent-= 0.9.0.jar with status 404 Not Found: <html>
```
Gotta check why the check did not fail in the PR #160
> chore(Dockerfile) correct the DD_AGENT download

- build.gradle.kts
Caused by https://github.com/jenkins-infra/account-app/pull/143
see https://github.com/jenkins-infra/helpdesk/issues/3195
I'm not 100% sure what's going on here.
Locally I got `java.lang.NoClassDefFoundError: com/sun/mail/util/MailLogger`
In production it's getting `com.sun.mail.smtp.SMTPSendFailedException: 550 Unauthenticated senders not allowed`
I was able to reset the users password from my local machine port forwarding to prod ldap with this change
> Use a mail implementation not api

- src/main/resources/org/jenkinsci/account/Application/index.jelly
While the current wording is not wrong in any kind, it's not much of use for the ordinary Jenkins plugin or library developer. You can't do anything with your LDAP account on ci.j, unless you have specific permission.
Job configuration happens exclusively through your Jenkinsfile, not through the web UI.
> Replace ci.jenkins.io with Artifactory URL

- src/main/java/org/jenkinsci/account/Application.java
- src/main/resources/org/jenkinsci/account/Application/signup.jelly
Evaluating use cases during signup for internal infrastructure isn't much of use, if I'm not mistaken. Let's get a rid of it to simplify the signup process.
> Remove signup survey

- src/main/resources/org/jenkinsci/account/Application/signup.jelly
A small fix up, to align the email and confirmation field layout.
**Before**:
**After**:
> Fix email field signup spacing

- Dockerfile
- Jenkinsfile
- build.gradle.kts
- settings.gradle.kts
- src/it/java/org/jenkinsci/account/ui/admin/ResetPasswordAdminTest.java
- src/it/java/org/jenkinsci/account/ui/email/ReadInboundEmailService.java
- src/it/java/org/jenkinsci/account/ui/resetpassword/ResetPasswordTest.java
- src/main/java/org/jenkinsci/account/AdminUI.java
- src/main/java/org/jenkinsci/account/Application.java
- I've ran all the recent regression tests that I've added
- I've manually checked sign-up as that's not tested yet
- I've built the docker image and sanity checked the app using the `docker compose` file (logged in)
first I tried jetty 11 but we can't upgrade to that till:
- stapler is updated to support jakarta
- the captcha library is dropped / upgraded / replaced
> Upgrade to Jetty 10, Java 17, Jakarta dependencies

- Dockerfile
- README.md
- build.gradle.kts
- docker-compose.yaml
- entrypoint.sh
- src/main/java/org/jenkinsci/account/Application.java
Fixes https://github.com/jenkins-infra/account-app/issues/185
We don't need this because we auto-create users on initial Jira login, this functionality was added before Jira had that feature.
All maintainers need to login to Jira before they can host a plugin / be mentioned in RPU.
> Remove Jira sync

- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
Loading from webjars needs to be kept in sync with the dependencies shaded according to build.gradle.kts, we can't reference a path that does not exist.
Additionally, this PR fixes the version of lit. I assume we wanted to call 2.4.0 back then because there's no 3.x release available.
> Update JQuery, webcomponentsjs and fix lit version

- .github/ISSUE_TEMPLATE/1-bug.yml
- .github/ISSUE_TEMPLATE/2-enhancement.yml
- .github/ISSUE_TEMPLATE/3-documentation.yml
- .github/ISSUE_TEMPLATE/config.yml
- src/main/resources/org/jenkinsci/account/taglib/layout.jelly
This PR utilizes a recent jio addition allowing you to specify template the footer should link to, in case you want to report an issue with a page.
> Add repo to footer and enable GH issue forms

- src/main/java/org/jenkinsci/account/Application.java
As the Jenkins Infra team does not have and does not want access to admin@jenkins-ci.org but still needs to deal with account issues, this PR is adding a log when a signup is blocked for any antispam reason.
> feat: log when a signup is blocked for any antispam reason

- Dockerfile
- src/main/java/org/jenkinsci/account/Application.java
- src/main/java/org/jenkinsci/account/Parameters.java
- src/main/java/org/jenkinsci/account/WebAppMain.java
- src/main/java/org/jenkinsci/account/config/MailConfig.java
- src/main/resources/application.conf
Allow to configure the sender email address instead of using the hardcoded `admin@jenkins-ci.org` email address.
Also replace the `Admin` default sender name by `Jenkins Accounts`.
> feat: allow configuring the sender email address

- src/main/java/org/jenkinsci/account/Application.java
Currently the provided SMTP port parameter isn't respected when the `useAuth` setting is set to `true`.
This PR removes its replacement to `587` in such case.
> chore: do not override the provided SMTP port with an hardcoded value when setting an auth

- Jenkinsfile
Ref: https://github.com/jenkins-infra/helpdesk/issues/3619#issuecomment-1713522131
EDIT: the arm64 is already built on infra.ci.jenkins.io since https://github.com/jenkins-infra/account-app/pull/299, this PR also builds it on ci.jenkins.io
> chore: add arm64 image to ci.jenkins.io build

- Jenkinsfile
- Jenkinsfile_k8s
This PR disables tagging and publication of docker image and github release from ci.jenkins.io
The merge of this PR will also serve as a test for https://github.com/jenkins-infra/pipeline-library/pull/784
Ref:
- https://github.com/jenkins-infra/account-app/pull/339#issuecomment-1872404386
> chore: disable publication from ci.jenkins.io

- src/main/java/org/jenkinsci/account/Application.java
We recently had 2 accounts creations blocked due to a `likely spam: BL: IP` error: Users had public IPs in the `180.151.*` range:
- https://github.com/jenkins-infra/helpdesk/issues/4077
- https://github.com/jenkins-infra/helpdesk/issues/4083
This PR removes the range from the IPv4 deny list and adds back the former IPs identified as spammers 9 years ago with comments to document.
> feat(anti-spam) unblock the `180.151.*` range

- src/main/java/org/jenkinsci/account/Myself.java
Previously, there was no size limit for the last name field, which could lead to unexpected behaviour. This commit sets a maximum length of 100 characters for both first and last names.
Fixes jenkins-infra/helpdesk#1813
> Fix INFRA-2178 | Enforce 100-character limit for first and last name

- docker-compose.yaml
- mock-ldap/Dockerfile
- mock-ldap/data.ldif
The mock LDAP for Jenkins, which is present at https://github.com/jenkins-infra/mock-ldap, has been added so that the image is freshly built each time. I also updated the docker-compose.yaml to point it to the newly added Dockerfile. I also removed the image attribute from accountapp service in docker-compose since it doesn't exist on the Docker hub anymore.  
This has been done as per the discussion here https://github.com/jenkins-infra/mock-ldap/issues/5
> Added Mock LDAP

- Jenkinsfile
As per - https://github.com/jenkins-infra/helpdesk/issues/2778
`automaticSemanticVersioning` is set to true by default, we no longer need to set the parameter in the script call.
> chore(Jenkinsfile): Remove automaticSemanticVersioning from script call
